backend = "glx";
vsync = true;
use-damage = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

shadow = true;
shadow-radius = 14;
shadow-opacity = 0.36;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-color = "#232634";

fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 8;

corner-radius = 6;

blur-method = "none";

rules: ({
  match = "window_type = 'dock' || "
          "window_type = 'desktop' || "
          "class_g = 'Dunst' || "
          "class_g = 'i3lock' || "
          "class_g = 'Rofi' || "
          "name = 'rofi' || "
          "class_g = 'slop' || "
          "class_g = 'maim'";
  shadow = false;
  fade = false;
  corner-radius = 0;
}, {
  match = "window_type = 'tooltip' || "
          "window_type = 'popup_menu' || "
          "window_type = 'dropdown_menu' || "
          "window_type = 'menu'";
  shadow = true;
  opacity = 1.0;
  corner-radius = 4;
}, {
  match = "window_type = 'dock' || "
          "window_type = 'desktop'";
  blur-background = false;
});
