Net/ThemeName "catppuccin-frappe-mauve-standard+default"
Net/IconThemeName "Adwaita"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 24
Gtk/FontName "JetBrains Mono 10"
Gtk/DecorationLayout ":"
Gtk/EnableAnimations 1
Net/EnableEventSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
